version: '3'

services:
  app:
    container_name: acallme_app
    image: node:latest
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: acallme
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
