version: '3'

services:
  app:
    container_name: acallme_app
    image: node:latest
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: acallme_db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5365:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acallme
    networks:
      - app-network

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: acallme_db_insight
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data

    networks:
      - app-network

  cache:
    image: redislabs/rejson:latest
    restart: unless-stopped
    container_name: acallme_cache
    ports:
      - '6381:6379'
    networks:
      - app-network
      - cache-network

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    container_name: acallme_cache_insight
    ports:
      - '8001:8001'
    volumes:
      - cache-data:/var/lib/redis/data
    networks:
      - cache-network

volumes:
  cache-data:
  db-data:

networks:
  app-network:
    driver: bridge
  cache-network:
    driver: bridge
