version: "3"

services: 
	app:
		container_name: acallme_app
		image: node:latest
		networks:
			- app-network
		volumes: 
			- .:/usr/src/app
		ports:
			- "3000:3000"
		depends_on: 
			- db

	db:
		image: postgres:latest
		container_name: postgres_db
		restart: unless-stopped
		volumes: 
			- db-data:/var/lib/postgresql/data
		ports: 
			- "5365:5432"
		environment: 
			POSTGRES_USER: postgres
			POSTGRES_PASSWORD: postgres
			POSTGRES_DB: acallme
		networks: 
			- app-network

volumes: 
	db-data

networks:
	app-network:
		driver: bridge
